apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker-service
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: gs-spring-boot-docker
  type: NodePort